name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Required to push to the output branch

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: pratham735505
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
